DEBUG 2025-06-10 02:47:57,826 views 20396 3760 Home page accessed by authenticated user
INFO 2025-06-10 02:48:11,460 views 20396 3760 Dashboard accessed by staff member VLAD9205
DEBUG 2025-06-10 02:58:20,371 views 3412 25652 Product list accessed
INFO 2025-06-10 02:58:24,651 views 3412 25652 Order creation initiated by user VLAD9205
ERROR 2025-06-10 02:58:24,651 views 3412 25652 Error in order_create view: BaseModelForm.__init__() got an unexpected keyword argument 'user'
Traceback (most recent call last):
  File "C:\Users\LENOVO\Lab5\main\views.py", line 625, in order_create
    form = OrderForm(user=request.user)
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
DEBUG 2025-06-10 02:58:36,254 views 3412 25652 Product list accessed
INFO 2025-06-10 02:58:46,291 views 3412 25652 Order creation initiated by user VLAD9205
ERROR 2025-06-10 02:58:46,292 views 3412 25652 Error in order_create view: BaseModelForm.__init__() got an unexpected keyword argument 'user'
Traceback (most recent call last):
  File "C:\Users\LENOVO\Lab5\main\views.py", line 625, in order_create
    form = OrderForm(user=request.user)
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
DEBUG 2025-06-10 02:59:46,455 views 14456 180 Product list accessed
DEBUG 2025-06-10 03:04:58,174 views 9268 23380 Product list accessed
INFO 2025-06-10 03:13:08,368 views 12292 7124 Order creation initiated by user VLAD9205
INFO 2025-06-10 03:13:12,476 views 12292 7124 Order creation initiated by user VLAD9205
DEBUG 2025-06-10 03:13:19,665 views 12292 7124 Product list accessed
DEBUG 2025-06-10 03:14:12,479 views 25224 9672 Product list accessed
DEBUG 2025-06-10 03:15:26,996 views 25224 9672 Product list accessed
DEBUG 2025-06-10 03:22:09,460 views 9000 2204 Product list accessed
DEBUG 2025-06-10 03:22:14,262 views 9000 2204 Home page accessed by authenticated user
DEBUG 2025-06-10 03:22:20,388 views 9000 2204 Product list accessed
DEBUG 2025-06-10 03:32:32,025 views 2224 9004 Product list accessed
INFO 2025-06-10 03:32:38,227 views 2224 9004 Order creation initiated by user scarlett
DEBUG 2025-06-10 03:36:22,462 views 22156 21528 Home page accessed by authenticated user
DEBUG 2025-06-10 03:36:28,226 views 22156 21528 Product list accessed
INFO 2025-06-10 03:37:55,487 views 22156 21528 Order creation initiated by user scarlett
INFO 2025-06-10 03:39:26,966 views 22156 21528 Order creation initiated by user scarlett
INFO 2025-06-10 03:39:49,848 views 22156 21528 Order creation initiated by user scarlett
INFO 2025-06-10 03:45:37,834 views 22436 22760 Order creation initiated by user scarlett
ERROR 2025-06-10 03:45:37,836 views 22436 22760 Error in order_create view: no such column: main_product.description
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_product.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LENOVO\Lab5\main\views.py", line 652, in order_create
    for p in products
             ^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_product.description
DEBUG 2025-06-10 03:45:41,256 views 22436 22760 Product list accessed
ERROR 2025-06-10 03:45:41,286 views 22436 22760 Error in product_list view: Reverse for 'glossary' not found. 'glossary' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "C:\Users\LENOVO\Lab5\main\views.py", line 798, in product_list
    return render(request, 'main/product_list.html', {
        'products': qs,
    ...<6 lines>...
        'user_authenticated': request.user.is_authenticated,
    })
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'glossary' not found. 'glossary' is not a valid view function or pattern name.
DEBUG 2025-06-10 03:45:44,076 views 22436 22760 Home page accessed by authenticated user
ERROR 2025-06-10 03:45:46,366 views 22436 22760 Error in home view: Reverse for 'glossary' not found. 'glossary' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "C:\Users\LENOVO\Lab5\main\views.py", line 290, in home
    return render(request, 'main/home.html', {
        'latest': latest,
        'quote': quote,
        'joke': joke,
    })
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'glossary' not found. 'glossary' is not a valid view function or pattern name.
DEBUG 2025-06-10 03:46:16,078 views 22320 392 Home page accessed by authenticated user
ERROR 2025-06-10 03:46:17,908 views 22320 392 Error in home view: Reverse for 'glossary' not found. 'glossary' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "C:\Users\LENOVO\Lab5\main\views.py", line 290, in home
    return render(request, 'main/home.html', {
        'latest': latest,
        'quote': quote,
        'joke': joke,
    })
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'glossary' not found. 'glossary' is not a valid view function or pattern name.
DEBUG 2025-06-10 03:46:21,062 views 22320 392 Product list accessed
ERROR 2025-06-10 03:46:21,067 views 22320 392 Error in product_list view: Reverse for 'glossary' not found. 'glossary' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "C:\Users\LENOVO\Lab5\main\views.py", line 798, in product_list
    return render(request, 'main/product_list.html', {
        'products': qs,
    ...<6 lines>...
        'user_authenticated': request.user.is_authenticated,
    })
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'glossary' not found. 'glossary' is not a valid view function or pattern name.
DEBUG 2025-06-10 03:48:00,810 views 22320 392 Home page accessed by authenticated user
DEBUG 2025-06-10 03:48:07,470 views 22320 392 Product list accessed
INFO 2025-06-10 03:48:45,924 views 22320 392 Order creation initiated by user scarlett
INFO 2025-06-10 03:48:56,631 views 22320 392 Order creation initiated by user scarlett
DEBUG 2025-06-10 03:50:38,742 views 22320 392 Product list accessed
DEBUG 2025-06-10 03:50:43,193 views 22320 392 Product list accessed
DEBUG 2025-06-10 03:50:43,194 views 22320 392 Product filter by category: 3
DEBUG 2025-06-10 03:50:48,730 views 22320 392 Product list accessed
DEBUG 2025-06-10 03:50:52,199 views 22320 392 Product list accessed
DEBUG 2025-06-10 03:50:52,199 views 22320 392 Product filter by manufacturer: 3
DEBUG 2025-06-10 03:50:55,663 views 22320 392 Product list accessed
DEBUG 2025-06-10 03:50:55,664 views 22320 392 Product filter by manufacturer: 3
DEBUG 2025-06-10 03:51:00,167 views 22320 392 Product list accessed
DEBUG 2025-06-10 03:51:00,167 views 22320 392 Product filter by manufacturer: 3
DEBUG 2025-06-10 03:51:11,777 views 22320 392 Product list accessed
INFO 2025-06-10 03:51:11,777 views 22320 392 Product search query: 1234
DEBUG 2025-06-10 03:51:19,081 views 22320 392 Product list accessed
INFO 2025-06-10 03:52:44,491 views 22320 392 Order creation initiated by user scarlett
DEBUG 2025-06-10 03:54:13,754 views 22320 392 Home page accessed by authenticated user
DEBUG 2025-06-10 03:54:21,069 views 22320 392 Product list accessed
INFO 2025-06-10 03:56:31,491 views 23096 8376 Order creation initiated by user scarlett
DEBUG 2025-06-10 03:56:34,443 views 23096 8376 Product list accessed
INFO 2025-06-10 03:56:38,138 views 23096 8376 Order creation initiated by user scarlett
INFO 2025-06-10 03:56:52,088 views 23096 8376 Order creation initiated by user scarlett
INFO 2025-06-10 03:59:06,684 views 23096 8376 Order creation initiated by user scarlett
INFO 2025-06-10 04:00:25,278 views 23096 8376 Order creation initiated by user scarlett
ERROR 2025-06-10 04:00:25,280 views 23096 8376 Error in order_create view: 'form-TOTAL_FORMS'
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'form-TOTAL_FORMS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\Lab5\main\views.py", line 647, in order_create
    total_forms = int(formset.data['form-TOTAL_FORMS'])
                      ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'form-TOTAL_FORMS'
INFO 2025-06-10 04:02:09,220 views 11964 25752 Order creation initiated by user scarlett
INFO 2025-06-10 04:02:43,838 views 11964 25752 Order creation initiated by user scarlett
WARNING 2025-06-10 04:02:43,842 views 11964 25752 Invalid order form submission by scarlett
INFO 2025-06-10 04:02:55,389 views 11964 25752 Order creation initiated by user scarlett
WARNING 2025-06-10 04:02:55,390 views 11964 25752 Invalid order form submission by scarlett
INFO 2025-06-10 04:03:00,999 views 11964 25752 Order creation initiated by user scarlett
WARNING 2025-06-10 04:03:01,000 views 11964 25752 Invalid order form submission by scarlett
INFO 2025-06-10 04:03:05,788 views 11964 25752 Order creation initiated by user scarlett
WARNING 2025-06-10 04:03:05,789 views 11964 25752 Invalid order form submission by scarlett
INFO 2025-06-10 04:03:28,993 views 11964 25752 Order creation initiated by user scarlett
INFO 2025-06-10 04:03:53,392 views 11964 25752 Order creation initiated by user scarlett
INFO 2025-06-10 04:04:08,507 views 11964 25752 Order creation initiated by user scarlett
INFO 2025-06-10 04:05:15,959 views 11964 25752 Order creation initiated by user scarlett
WARNING 2025-06-10 04:05:15,961 views 11964 25752 Invalid order form submission by scarlett
INFO 2025-06-10 04:05:21,824 views 11964 25752 Order creation initiated by user scarlett
WARNING 2025-06-10 04:05:21,825 views 11964 25752 Invalid order form submission by scarlett
DEBUG 2025-06-10 06:22:39,965 views 3916 22812 Home page accessed by authenticated user
DEBUG 2025-06-10 06:22:44,687 views 3916 22812 Product list accessed
DEBUG 2025-06-10 06:32:14,892 views 23704 22188 Product list accessed
DEBUG 2025-06-10 06:32:17,891 views 23704 22188 Product list accessed
DEBUG 2025-06-10 06:32:29,442 views 23704 22188 Product list accessed
DEBUG 2025-06-10 06:32:31,896 views 23704 22188 Home page accessed by anonymous user
DEBUG 2025-06-10 06:33:08,755 views 23704 22188 Product list accessed
INFO 2025-06-10 06:33:34,612 views 23704 22188 Dashboard accessed by staff member VLAD9205
DEBUG 2025-06-10 06:34:06,314 views 23704 22188 Product list accessed
DEBUG 2025-06-10 06:35:57,168 views 23704 22188 Product list accessed
DEBUG 2025-06-10 06:36:04,519 views 23704 22188 Product list accessed
DEBUG 2025-06-10 06:36:11,479 views 23704 22188 Product list accessed
DEBUG 2025-06-10 06:36:13,863 views 10360 24240 Product list accessed
DEBUG 2025-06-10 06:41:37,579 views 22884 20804 Product list accessed
DEBUG 2025-06-10 06:43:48,077 views 25504 17412 Product list accessed
DEBUG 2025-06-10 06:43:54,307 views 25504 17412 Product list accessed
DEBUG 2025-06-10 06:46:13,070 views 25568 25144 Product list accessed
DEBUG 2025-06-10 06:52:27,881 views 9540 2216 Product list accessed
DEBUG 2025-06-10 06:52:36,597 views 9540 2216 Product list accessed
INFO 2025-06-10 06:53:46,259 views 9540 2216 Dashboard accessed by staff member VLAD9205
DEBUG 2025-06-10 06:54:28,233 views 9540 2216 Product list accessed
DEBUG 2025-06-10 06:57:36,377 views 8588 23292 Product list accessed
INFO 2025-06-10 06:57:38,240 views 8588 23292 Dashboard accessed by staff member VLAD9205
INFO 2025-06-10 06:57:46,636 views 8588 23292 Dashboard accessed by staff member VLAD9205
INFO 2025-06-10 06:57:50,612 views 8588 23292 Dashboard accessed by staff member VLAD9205
DEBUG 2025-06-10 06:58:06,553 views 8588 23292 Product list accessed
DEBUG 2025-06-10 06:58:13,703 views 8588 23292 Product list accessed
